In [7]:
import tensorflow as tf
import pandas as pd
import numpy as np

In [8]:
tf.__version__

'2.19.0'

In [11]:
tf.test.is_gpu_available()

False

In [12]:
#creating integer constant
tf.constant(10)

<tf.Tensor: shape=(), dtype=int32, numpy=10>

In [13]:
#creating float constant
tf.constant(10.2)

<tf.Tensor: shape=(), dtype=float32, numpy=10.199999809265137>

In [14]:
#creating string constant
tf.constant("you can do anything")

<tf.Tensor: shape=(), dtype=string, numpy=b'you can do anything'>

In [15]:
#creating boll constant
tf.constant(True)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [16]:
#Create constant Numpy array / List / Tuple
np_arr = tf.constant(np.array([1,2,3,4,5,6]))
np_arr

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

In [17]:
#create 1D array
tf.constant(np.array([1,2,3,4,5,6]))

<tf.Tensor: shape=(6,), dtype=int64, numpy=array([1, 2, 3, 4, 5, 6])>

In [20]:
#create 2D array
tf.constant(np.ones((2,2)))

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[1., 1.],
       [1., 1.]])>

In [24]:
#creating 3D array
r = tf.constant([[[1,2],[3,4],[5,6]]])
r

<tf.Tensor: shape=(1, 3, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)>

In [25]:
#type of constant
type(r)

tensorflow.python.framework.ops.EagerTensor

In [26]:
#shape of tensor
r.shape

TensorShape([1, 3, 2])

In [27]:
#Access constant value
r.numpy()

array([[[1, 2],
        [3, 4],
        [5, 6]]], dtype=int32)

In [ ]:
#Slicing
r.numpy()[0,2]

array([5, 6], dtype=int32)

In [29]:
#constant datatype
r.dtype

tf.int32